export interface APIResponse<T> {
  success: boolean;
  message: string;
  body?: T;
}

export interface LoginResponseBody {
  accessToken: string;
  refreshToken: string;
  expires_in: number;
  refresh_expires_in: number;
}

export type FetchQueryParams = {
  endpoint: string;
  queryKey: string;
  type?: 'basic-auth' | 'token';
  headers?: Record<string, string>;
};

export interface UploadResponse {
  _id: string;
  phone: string;
  tablet: string;
  desktop: string;
  createdAt: string;
  updatedAt: string;
  __v: number;
}

// Generated by https://quicktype.io

export interface AddProductPayload {
  title: string;
  description: string;
  price: string;
  summary: string;
  storeName: string;
  coverImageId: string;
  thumbnailId: string;
  additionalInformation: AdditionalInformation[];
  term: Term;
  options: {
    price: string;
    duration: string;
    type: string;
  }[];
}

export interface AdditionalInformation {
  attribute: string;
  value: string;
}

export interface Term {
  title: string;
  description: string;
}

export interface AddProductResponse {
  product: Product;
}

export interface Product {
  title: string;
  description: string;
  price: string;
  summary: string;
  uid: string;
  merchant: Merchant;
  additionalInformation: string[];
  option: Option[];
  _id: string;
  createdAt: string;
  updatedAt: string;
  __v: number;
}

export interface Merchant {
  _id: string;
  storeName: string;
  customer: string;
  createdAt: string;
  updatedAt: string;
  __v: number;
}

export interface Option {
  price: Price;
  duration: string;
  type: string;
  _id: string;
  createdAt: string;
  updatedAt: string;
  __v: number;
}

export interface Price {
  $numberDecimal: string;
}

// Generated by https://quicktype.io

export interface AddAffiliatePayload {
  email: string;
  list: { commission: number; productId: string }[];
}

// Generated by https://quicktype.io

export interface Affliate {
  _id: string;
  status: string;
  type: string;
  uid: string;
  commission: number;
  link: string;
  affiliateCustomer: string;
  product: string;
  merchant: string;
  createdAt: string;
  updatedAt: string;
  __v: number;
}

// Generated by https://quicktype.io

export interface Merchant {
  _id: string;
  storeName: string;
  customer: string;
  createdAt: string;
  updatedAt: string;
  __v: number;
}

export interface MerchantProductsResponse {
  merchant: Merchant;
  product: MerchantProduct[];
}

export interface TImage {
  _id: string;
  phone: string;
  tablet: string;
  desktop: string;
  createdAt: string;
  updatedAt: string;
  __v: number;
}

export interface MerchantProduct {
  _id: string;
  title: string;
  description: string;
  price: string;
  summary: string;
  uid: string;
  merchant: string;
  additionalInformation: AdditionalInformation[];
  term: Term;
  coverImage: TImage;
  thumbnail: TImage;
  option: Option[];
  createdAt: string;
  updatedAt: string;
  __v: number;
}

// Generated by https://quicktype.io

export interface Term {
  _id: string;
  title: string;
  description: string;
  createdAt: string;
  updatedAt: string;
  __v: number;
}

export interface AdditionalInformation {
  _id: string;
  attribute: string;
  value: string;
  createdAt: string;
  updatedAt: string;
  __v: number;
}

export interface Option {
  _id: string;
  price: Price;
  duration: string;
  type: string;
  createdAt: string;
  updatedAt: string;
  __v: number;
}

export interface Price {
  $numberDecimal: string;
}
